### ISSUE TITLE
Feature Request: Transactions by address. 

### ISSUE THREAD

**Issue by hkey0** [Zondax/namadexer#101]
Hello, I have a few ideas about improving namadexer. 

- List of transactions of the specified transparent address. 
- List of all validators (with total stake)

It would be great if it had these features.

**Comment by rllola** [comment]
Hey @hkey0 

Looks like good ideas. We will work on this ASAP.

**Comment by rllola** [comment]
> List of transactions of the specified transparent address.

Unfortunately today we don't have all the decrypted info in a table so researching through addresses will return incomplete answer. However there is a solution proposed by my colleague to store the arbitrary data as JSON and postgres could handle searching in the JSON string. However it could impact negatively the performances.

**Comment by hkey0** [comment]
> > List of transactions of the specified transparent address.
> 
> Unfortunately today we don't have all the decrypted info in a table so researching through addresses will return incomplete answer. However there is a solution proposed by my colleague to store the arbitrary data as JSON and postgres could handle searching in the JSON string. However it could impact negatively the performances.

that's sad to hear. is there any way to link wrapper tx to inner tx? so how can I access the inner tx of the wrapper tx

**Comment by rllola** [comment]
> Can't we see all transactions of transparent addresses? Why can't we do that?
Because the addresses are in the blob of data and we don't know how to look them up in sql. Unless like mentioned we store it in JSON.

We are currently looking at this approach.

**Comment by hkey0** [comment]
> > Can't we see all transactions of transparent addresses? Why can't we do that?
> 
> Because the addresses are in the blob of data and we don't know how to look them up in sql. Unless like mentioned we store it in JSON.
> 
> We are currently looking at this approach.

Is it possible to use the tx search in cometbft? 
**Querying Transactions Events:** https://docs.cometbft.com/v0.37/app-dev/indexing-transactions

**Comment by opsecx** [comment]
> > Can't we see all transactions of transparent addresses? Why can't we do that?
> 
> 
> 
> Because the addresses are in the blob of data and we don't know how to look them up in sql. Unless like mentioned we store it in JSON.
> 
> 
> 
> We are currently looking at this approach.

aren't all the transactions already in a separate table? I can see all of them in the indexer currently? (pretor)

**Comment by rllola** [comment]
I have started to work on this.

@opsecx  In the current `main` branch we don't have the `tx_transfer` table anymore instead all the data are stored as JSON object in the `transactions` table. Also `tx_transfer` transaction might not represent all the transactions associated with an address. So now we can collect from all other kind of transactions.

I will share here the draft PR when it is ready.

**Comment by opsecx** [comment]
So all applications built to old format will fail if pulling the revised source tree? that's a lot of extra work on this end

**Comment by opsecx** [comment]
I have to say that breaking changes like these are extremely inconvenient

**Comment by rllola** [comment]
> So all applications built to old format will fail if pulling the revised source tree? that's a lot of extra work on this end

No there is no breaking changes on the endpoints. You should be all good.

**Comment by opsecx** [comment]
> > So all applications built to old format will fail if pulling the revised source tree? that's a lot of extra work on this end
> 
> 
> 
> No there is no breaking changes on the endpoints. You should be all good.

I'm drawing directly off the db, so I'm assuming the answer to the question is yes

**Comment by rllola** [comment]
Done with https://github.com/Zondax/namadexer/pull/161
