### ISSUE TITLE
Consider implementation of an ORM

### ISSUE THREAD

**Issue by dimiandre** [Zondax/namadexer#102]
Have you consider implementing an ORM system like diesel? 

Creating join and complex api routes using SQLx only is not super trivial and having an ORM could simplify this

what do you think?

**Comment by neithanmo** [comment]
@dimiandre 
Given our current focus on managing blockchain data indexing, which primarily involves write-once, read-many operations, and the ongoing process of defining complex read queries, incorporating ORMs at this juncture might not be the most efficient approach. ORMs, while beneficial for abstracting database interactions and simplifying CRUD operations, may not offer the same level of efficiency for complex queries that our project might requires, I mean we are still exploring all the useful queries we would need to make this indexer easy and usable. 

As our database interactions are predominantly read-oriented with fixed data, the overhead and potential complexity added by an ORM may not justify its use, We should finalize our query requirements to ensure our system is optimized for high-read efficiency and consider ORMs once our querying needs are fully understood  without compromising performance.
