### ISSUE TITLE
decrypt tx data

### ISSUE THREAD

**Issue by msobh13** [Zondax/namadexer#103]
would be better to show text data in human readable format

**Comment by msobh13** [comment]
is it even possible?

**Comment by rllola** [comment]
When queried from the server you will have the decryoted data formated as JSON. We store it as blob for efficiency.

**Comment by msobh13** [comment]
I tried to access the tx hash data  using 
http://192.168.1.223:30303/tx/49484c9f70d5e2a9463b0fc06411a38b4036baaf294e5739fb52f6894f1a3193
but the section data is encrypted 

ex:
`"data": "7100000000718d6108ef5e4f9228ddcd4bc2cde98ecc6a0f3f4a025adc1c5d445b8ffb52169f10dae3023f340090135c5d0200000000000000000000000000000000000000000000000000000595afd3df45232267e89631d3353113df5e49d4ee9bf47590e94d21`

How to decrypt  these data

**Comment by rllola** [comment]
Can you share the full response ?

**Comment by msobh13** [comment]
this for this hash `49484c9f70d5e2a9463b0fc06411a38b4036baaf294e5739fb52f6894f1a3193`

in block 2   Chain ID:  shielded-expedition.88f17d1d14


`{
"hash": "49484c9f70d5e2a9463b0fc06411a38b4036baaf294e5739fb52f6894f1a3193",
"block_id": "8dc75c9a34c28729923b98821c5986444748e5184511ff2e9565b9c06de39542",
"tx_type": "Protocol",
"wrapper_id": "",
"fee_amount_per_gas_unit": null,
"fee_token": null,
"gas_limit_multiplier": null,
"code": "0000000000000000000000000000000000000000000000000000000000000000",
"data": "7100000000718d6108ef5e4f9228ddcd4bc2cde98ecc6a0f3f4a025adc1c5d445b8ffb52169f10dae3023f340090135c5d0200000000000000000000000000000000000000000000000000000595afd3df45232267e89631d3353113df5e49d4ee9bf47590e94d2145a734cccbea1070eed6650a404ff07864020000000000000000000000000000000000000000000000000000071d182a449367ee0c2826f33e9d420bf1cf51806c37e3eca0d7f9d071a227fb02427be731c52e54003c3758640200000000000000000000000000000000000000000000000000001002d00623ccf39eefb2fac85d6a77992f95a346525d0b54e4bdefc272167052213fbe19edb3cf00521bfb786402000000000000000000000000000000000000000000000000000011b8ff90204cc5d7a9616dc99a61be4deff41a2093bef2482e419507ccd0121aeb8cd1401e35d6c8003c37586402000000000000000000000000000000000000000000000000000012c9ebb71d1b7da229c5988451378900c3bd03547e2bfb1702bcab71ec75569024475a74c68cecb700a89c134602000000000000000000000000000000000000000000000000000015b2ce878a0b4cc77761c753fdf97c1fda607e7f4088f8048cc557f24ef7824cf4daa40a57aecb4b5280c896640200000000000000000000000000000000000000000000000000001d3a3d9d89ec493830245064ff1eb83d4ea7a26e06bad7c5923d18aa4ec3ab18e3e9432847f9a92c003c3758640200000000000000000000000000000000000000000000000000001dffbe852b79c03fe1731c386891c8121355a299eee178f2fd0de5054a9c112d123044cbd726bfbe003c3758640200000000000000000000000000000000000000000000000000001f8a915fe00c84381db9781625ba71fdcd8029d89d339e841d49e86c203e9ba7bd906177e56d83f9c082f2b36402000000000000000000000000000000000000000000000000000024465ece061574843933dc4641b9741c3543096a186c15a34273db1aa2bb2ffca9239be7be23e9ef003c37586402000000000000000000000000000000000000000000000000000024c49cd2656966b3fb70b398bad3cdf9ead96342ca330863f8f8ec09bac65595b575838004b1db58006b9fb16402000000000000000000000000000000000000000000000000000024ed8369e700645b77023a95c394665735beff6c3148d647e14e5b254a2a7b82697a23eb2348490d0090135c5d0200000000000000000000000000000000000000000000000000002889bd64791a4805a66cad3874552432bd1eae379104dbf532f40f75c5c19ca939f02e3608852de90010a5d4e80000000000000000000000000000000000000000000000000000002b92a3bdb7d6177967e95c0212d1e120888d17a2db54d0e8ce3fc522d8e15a59c6c1dcb7ef6d1a2e0090135c5d0200000000000000000000000000000000000000000000000000002b9d408800bbea328309a28b5c1f2d8370d74546c4ffbb0a8b31b0b38a1129e68c264fd07233667e006b9fb1640200000000000000000000000000000000000000000000000000002f6c3e28874f9a530bb757e72b5513cd2ec1b884550d41aa7b73b6b5e2e3221a4e3a37d6c9bc1b9a006b9fb1640200000000000000000000000000000000000000000000000000003271c51ffabd885e0644cf27e65e81fd93ae16efef59b61bdfd61272c86ecfd1b1186584e64eca2a003c3758640200000000000000000000000000000000000000000000000000003729c1f717828d971fc179178005b0734582390ffbde80c7b18648602242521ad1f91c1e8c68fa1f003c37586402000000000000000000000000000000000000000000000000000037b1e9f151dcc1b93bd8a320a96efe24567bcb5f48d6cc63f81a39cac235f5c891ceef463a2f168040d3c7906402000000000000000000000000000000000000000000000000000039159c4344fcbd87f935b28a7b1a6cf9a18da1e62029b27e40ffa28500536b2c22bd3b58cde97fb80090135c5d020000000000000000000000000000000000000000000000000000398213279af7e2da6386e8d865adc614b2957be0b8e4321c18e9983b96a321a9e8a5e3baaf9301420010a5d4e80000000000000000000000000000000000000000000000000000003c6df3b8ef61949ea8f43590f83bb6a37ac9d9347ac93a50fbaa182f416375ae16f4fd953ae8719d0010a5d4e80000000000000000000000000000000000000000000000000000003c72c1f650394ec52ea6a95223cd5ac1c61b77a2ce0d97e5ed2a69b410490bc6026c6985388902bc40e31cb36402000000000000000000000000000000000000000000000000000041eb606f91c9c3d818fa6f868f0374c414c2eeb07e0b948db54c898248edb6b7ed1bebed9d95513d0090135c5d0200000000000000000000000000000000000000000000000000004482deb881fff6fae178982497bda0fd0d59c689c2979334482aec5b95aee1a68951ec227a2f26b340198bb46402000000000000000000000000000000000000000000000000000047044961875b016c83365fb415335ab4f22cdf254e973972cbf7dabfe108c7f51eb7dfe3bd0f624740b6ebb1640200000000000000000000000000000000000000000000000000004719eb43ca11dc00afd02bf43d3cf462a79a1d8d0ecf32d6ecad88cbf257c6e8f1ae2ca8a08a65b700a89c13460200000000000000000000000000000000000000000000000000004af2ce1f2e0b648c35b40830bf98c2247e0f68ba39b6df968845ccc189840d9e087358cd5ee62064003c3758640200000000000000000000000000000000000000000000000000004e876cb12bbdb00cc01e93ee6cff760fa9ea36dac973c2890ccb5f266de2b7bbcaf673fcc47e9f5000d77bb4640200000000000000000000000000000000000000000000000000004f2c60cb8afbd634254ec89e3eb3ed522bbf12e22445bd1ed67234ec86c97165ce0fe0bd895e15f50006d29364020000000000000000000000000000000000000000000000000000502baa6b596859f8a901aaa6a579590e4fbc21ba257d52b3cbf6825b36292ad941697b93ee742ec400d77bb46402000000000000000000000000000000000000000000000000000051e6d0a5eb224fe2a81410b32b1b8c051716a5d5cd7d6aab6beeac2118449e9cda1b492e2e2ac236003c37586402000000000000000000000000000000000000000000000000000057e3a321076edd6e03286822b79fbeb6b6a1d3a80a151b05b31fe7b1333184867307a295077272f040198bb46402000000000000000000000000000000000000000000000000000058be074eb5c3ea79ac50cf1c87f73fb74759a034cb618e0fb1a7dd256a83f496beae4dff7e749a80003c3758640200000000000000000000000000000000000000000000000000005e1a200f8a2a45651396223502111f9927d97555c3c288609944af5349d58f261589d42fb0fa591f00c501b4640200000000000000000000000000000000000000000000000000005f8e1b189bb80d83ac63a680ed0530e7816e3bca1d104d5443af2726dfe1560530933f1cdac5248a40198bb464020000000000000000000000000000000000000000000000000000606dfdb05c9c569333da89892278b756e7d659ca5d840b8aeb4af3f7dab9b51ab2bec988a5e32cde003c375864020000000000000000000000000000000000000000000000000000615a1f15d822c9c99c63291a4316936a206a2f64cc082a544c2f03666dd8870c2326cdb6fd80e6ad0010a5d4e800000000000000000000000000000000000000000000000000000064b1c8076b4e7c8363b486d0b9d76e29751d56f9a4fc520d279f3c617b022d0a40f82fbe13d53324003c375864020000000000000000000000000000000000000000000000000000678daa66d3722c039221bbf4f31c0fbcaafafdaffd3b46afab8578940bd9c738c7ce46c0570668c4c082f2b3640200000000000000000000000000000000000000000000000000006ec528325a5ce85cb766a6397949fc4b14751f3a99eb0478c752c84ba9d6488f37cbc5d9cabbf8cc00a89c134602000000000000000000000000000000000000000000000000000072b1020e9d5a5f56c4099dd443446f94c44b8d868be29cd216e2ca5bed67ec54245853eee5c4369a00c501b46402000000000000000000000000000000000000000000000000000072f82d59b5908d445e4dba2a396e559964017fd10e4bcf793fd6593238c65d766e49d367fed33152c0946cb4640200000000000000000000000000000000000000000000000000007694273eead1b571269ce1b24d20722b7682a32296d9bc95c66872d723ec9f9bf551d9c15edc4f3500c501b4640200000000000000000000000000000000000000000000000000007828d22d18005ee644b28581d04ddf71b794273fc3a6d2f028a66b55b8ce24eeb9d826eb8c56f56a003c3758640200000000000000000000000000000000000000000000000000007863a7020dc7734d82aeeffec511e6b01ed3d40b0537879c509b36d75735315e927862c58c82a7b7003c3758640200000000000000000000000000000000000000000000000000007932fd5bc34e2a725b52afcefa8099487649479cad42279c4e42a86de3a06323164c59e4ccd53984006b9fb1640200000000000000000000000000000000000000000000000000007b0f3c147e85fcbd2e6118c1a0333ca3cec004fae0c2c6133fedc7c8db87d3fa3c20fe293987cd6500f098bd610200000000000000000000000000000000000000000000000000007d6b108b876445823e159c82db0ca0537ddeccfc3a857eb7b0d5a2242c8315bd1d8a1cba39e3c5650090135c5d0200000000000000000000000000000000000000000000000000007f493d8f241e068920f7f7fe67820bf0e7cdad1e4e1eb6d8e57a2d90ba047bb5e8b344f6467b1b84404ff078640200000000000000000000000000000000000000000000000000007ffa20eec5dd5e7f76f6d9cb5d977005049988e1306bddc0f2c11b7a7d425051899f713984a2cb39003c37586402000000000000000000000000000000000000000000000000000080883569e3750f4623714f6edda5e811650a5d30738fc138ae78cac16235eaaed8772003f8682500006b9fb16402000000000000000000000000000000000000000000000000000081624cb75b10a3a8c589a87edbb4dfecd517c7575014a6305bb1055ff9260d54bd877bb1423cffe40090135c5d02000000000000000000000000000000000000000000000000000081cbc62a5ee0a048154409f0b579397dfaa28231d38f3f07d873db08da270e4e98c359a42c937db200741fb05f020000000000000000000000000000000000000000000000000000860ac9bb308a8198111f484111979cb426d163b217a6ca14471bd966a3804c4aecb20744107d96d3003c375864020000000000000000000000000000000000000000000000000000873c6593624e0ce4fa8282be54c775bf16de1916de2e2c3afe282d464a251dc2832952bdc60c4e5e404ff078640200000000000000000000000000000000000000000000000000008745dfbb2d482e709d5798e8b73879c71cef75dd2be1de06fa83348974adc47ccc608c72123ca5ca005652615d020000000000000000000000000000000000000000000000000000886c39e5b6c6ed7601fab21b64d33a69890c65da1e6a98c5b695c5539e60562788b207984e67b989403ce8a764020000000000000000000000000000000000000000000000000000887392270b34b331299a71c7b1b2009ccd3bd4ebd5642df12459b96d125f54ed6c77eb6696d81e4d00d77bb46402000000000000000000000000000000000000000000000000000091314f1ff798671f7ea2e1ff4ea1f0a508b80c84b2a291aff7edc7c41b0fbc09225b4982c916ae62c082f2b3640200000000000000000000000000000000000000000000000000009165b52df384b977da0fcb27e901c1e046177500cc788661781b8065ac78a0d90a1e43aeeb92ec731237aab16402000000000000000000000000000000000000000000000000000097d3c80510e22188ca639ecf231a0338cafe5552564a51d30ab5e60ef96aa1839f2122093f49d80e404ff078640200000000000000000000000000000000000000000000000000009ac5f12bb8a921fd740e68d1dd1c048dad7ba74ca110dbdaba885e6db90302103ef918c70857213940198bb464020000000000000000000000000000000000000000000000000000a211f237ddcbaba98916e12dd0702e077032481a382144b941d89f69d0e2f25b07c6849a6c755853006b9fb164020000000000000000000000000000000000000000000000000000a2ca495a313ec0d3950b24137cd350c1a374be42c45af981f157f68c64d76142b6751ba1a7d1e260003c375864020000000000000000000000000000000000000000000000000000a5b848a4b27133457690ebedc1be0b8829853760909c60825f76e87be8ba205d373620391188cdfe0090135c5d020000000000000000000000000000000000000000000000000000a5bc017a60a2fa104d597d7fc8da786a25336209f9d8a0af20c79ae157c5272cdfb1a2b69327a5d5003c375864020000000000000000000000000000000000000000000000000000a5c7fa04cce9d2d41b92070240078f987068695fcfa2145b49f524842a950f135907e9c39e024a03003c375864020000000000000000000000000000000000000000000000000000a83f0fe655521c6324811e52d075eb357f53994954137ae2ab5d177a9b9cbb196f71d898e3dad2ca00c501b464020000000000000000000000000000000000000000000000000000abe78d3c0d667535ddfcef7ddc0864a5162018c99088a35cca589cc885f07419ecd382518596886600c501b464020000000000000000000000000000000000000000000000000000ac5a10ac2e2e7ed69731bf6e7c5836f3b99672e08096e286e06cc2ae5f199c28f5ca9a780b78fc9d0090135c5d020000000000000000000000000000000000000000000000000000ae5c56a68fb5cc5129880da8701000a31c5a859b5325daf46a2de0f46ddd2980926d12564ddf2f8c006b9fb164020000000000000000000000000000000000000000000000000000b1610844cb3c5da6ba9b6315359859d840cbeebf80139b59679fda78f3a67274b0663bde71bded120010a5d4e8000000000000000000000000000000000000000000000000000000b3efa57ad2d9e7ae4a8c1af4f537dce2e67dcb7c40c35f7f5ca6013028f25d9d894d25305855516c40198bb464020000000000000000000000000000000000000000000000000000b5ed9214e94dfdddb532eef647b93f3a34d00cd0a0167a65c06433b97f9e0620384b9ab1d9322e9e52e595b464020000000000000000000000000000000000000000000000000000b601f8ce38551a347e039a11b0ed9fea18d7d9ddb383647a4bc114f40754356db1d8f8f9b43e598e0090135c5d020000000000000000000000000000000000000000000000000000b7f22995f13ce5676a611ab7edf7075d45a9c6701f59746fab8b0f7cc59a3c031a916dade7099bbf0090135c5d020000000000000000000000000000000000000000000000000000b8b92803749563964e50126463f84e654ff3a6f6dbe964221b3de7f039defb39c48b4d5efbac3605003c375864020000000000000000000000000000000000000000000000000000bbbc771249c5f3141872a125046bb8a899ba81f34625978e6a1486c2a41cc776c182f1b5bb3e2a0e00ca9a3b00000000000000000000000000000000000000000000000000000000bdb4d1c72f1554c6e35a35c7d817232e70deade56d673a925202ce7c0f2d4b618ba85ad6661abaa4006b9fb164020000000000000000000000000000000000000000000000000000c0f8183c6e72e5ea89840a826fccfec0a194021ac6cb25267254fa9aa7998e6c8d3c089eeb4cd52380eac5835d020000000000000000000000000000000000000000000000000000c4c3d0bd61b8f3bca791a537b1d290314d1d798e3a97a377230ada21959e7e6918bda92578feb952521bfb7864020000000000000000000000000000000000000000000000000000c75a6ff48770282b97e8307cb76e2ea51101607c7c8316707ab245548403548be17980fce5f600ef0031c3e4ac010000000000000000000000000000000000000000000000000000c81ed6cfd2d51082112970c8c8ebe9b67593fd819f935191cd8339e3e6b6e6ffc09aa4035ea7e863c002655864020000000000000000000000000000000000000000000000000000cf251606a2b697cfad58f7a8656f02e8db7cd511625ed2afa7fe4c6697c1396fe628e39160d380e400582b0462020000000000000000000000000000000000000000000000000000d19bf66344a0e9539247de5e341b908d809f907423a40ae9a62b4d92a4104e159572989d20e8200b00c501b464020000000000000000000000000000000000000000000000000000d295e817512145519bc3380e4c5c123b16dad0b90fe01124495e6ca5ffebe61d11b2f4bd2166e256003c375864020000000000000000000000000000000000000000000000000000d2cbe0640ca38a1ad7c066939efdc49a2156ca7a7064fb0b81f232412ad68249df0286bf7be7e7a040198bb464020000000000000000000000000000000000000000000000000000d3c049a62c1aac8815125e1473c4897a27d25d08a63b0bc7da0bd4fc097729a4a8c23172b0411b22c082f2b364020000000000000000000000000000000000000000000000000000d61137a6ad9105201d24c584be6d0ce2fef17500d77ae942dc75aedbc98a40bea93293b019e719e80010a5d4e8000000000000000000000000000000000000000000000000000000d618cb834925b99cb16fe8662b14e109d4f4edf0d7cf6efbd0365ac2968de86c8a9ecf8405b3bf32404ff07864020000000000000000000000000000000000000000000000000000d7a93233d8885d145a9cee3f3d79f2fdfeaeed374750a5c7d1cf2c765b4565baf1a3c6eac0be4bf1006b9fb164020000000000000000000000000000000000000000000000000000d85570c96900ebe1987d6bf5fe5a158ee20402b71e3ffc991056a932f66a56ac670212683d3a5fd100d77bb464020000000000000000000000000000000000000000000000000000dbf7d8ea953a19484cb9b119aee2dddce6247b3b9917c4f8be126f8cb281d59fe254858401cc9c100090135c5d020000000000000000000000000000000000000000000000000000dd5fe1fc5c90c4390b15f600a92365400ee1e4bd6cb9a26d9cbdbbf205aa94726d8ddfc8005712260010a5d4e8000000000000000000000000000000000000000000000000000000dee229a79728b5b349b7e5bb298a727fd48057beb5c0b7bde84796241390c4405bacb1a405ba31d8003c375864020000000000000000000000000000000000000000000000000000e07fb7c3ed021244f223bd5c3e9e76085420e877b91cee6c1356439a7822e1713cc041d5ba2bbad0003c375864020000000000000000000000000000000000000000000000000000e2bd6e4eb9d7e9516e16f1f9168ba80352eda159b27a849565519d439bf11648e4d7ee9c8f7a3aed0090135c5d020000000000000000000000000000000000000000000000000000e56a818c2ab7d4fb150028b7010250ca8f26e664a98b120d2142b550e6e5d27276ecb374c156a35f006b9fb164020000000000000000000000000000000000000000000000000000e79147756cfe4a02499168cb23bd76c15cdfebfc66e917de5d17fe91076e6214696c1cbbc8fd0d58003c375864020000000000000000000000000000000000000000000000000000eb0c9b7afe95c4bb82644d0d2c4d444bd7a8ce0ad7be3665e8cb9e2c3fac5c0a22ee486556f9fe790090135c5d020000000000000000000000000000000000000000000000000000ec8af844b6e878070dd25b614eff1f4dca4301d8cc9c889d9ffa4f99b93c76c7d0faae4caa8055f30090135c5d020000000000000000000000000000000000000000000000000000ee8cafdee407ed5334acfa628a98eb4721bed4a292942d029988a863954bd844e8a8901cda031f1a00741fb05f020000000000000000000000000000000000000000000000000000ef3464972fdb460c8dfbc04c0cc4951665b92904bc04a2c937c97faa9d11ab7aaa9a9ef59a70966e40198bb464020000000000000000000000000000000000000000000000000000ef73db93d4dd0fe9867e53faad5674373daa1d25daa036b0f92cef429489ceab255a7fa75a6b63ee00c501b464020000000000000000000000000000000000000000000000000000ef75bed1c9ed56a8a6332bbb6506e9f9d385d59daf2caedcfa8022824e9b9c049162c8820d6911e3006b9fb164020000000000000000000000000000000000000000000000000000f00c74e55ced08920a85368a801546a9151a5c102c1107b31db27783a62f6a0448f501e7fe3ce9b540adaeb164020000000000000000000000000000000000000000000000000000f921b7975c4ba5fa8785e402ec448867d5b2f152afc6bfa16a2833c1658a93f68bd539fc3ed11fb20010a5d4e8000000000000000000000000000000000000000000000000000000fa90ffe2982e1ce4a3f2553ca06cee71cf3dba21e6b3857783d453249a16b2f6444148948b48301a00c501b464020000000000000000000000000000000000000000000000000000fb3b3e0850b903171a797685164bf11aabf2ff9766aed923687476f1a643485b7861d5c4225ab9ea00c501b464020000000000000000000000000000000000000000000000000000fbf6945d2a0a4aa08df7eec17b5d655c4c274043745a6bacd746ad695aea518e371b1bb9465f4b3a40198bb464020000000000000000000000000000000000000000000000000000ff76a6f1c3482766e75ca5dec20ce017a90d8069be98bd81fe738847dfd9df76780b28bf37824d610090135c5d020000000000000000000000000000000000000000000000000000003dc8923007d7b6e8fdac7f01bed7e1f0521f842700000000000000000198bf637168ce38cafa1cb298760dd0f8a76cc136eba714b305012564ed10436654d4971de2f20d6bbb6befe13b84d7e242f62bd9c1010a4e39182c88a665171101",
"tx": null
}`

**Comment by rllola** [comment]
Oh ok. It is a `Protocol` transaction. We don't have the information on how to decode. I don't think it is possible or if it is is not trivial.

**Comment by msobh13** [comment]
Aha ok got you . once chain resume i will check other tx and see if it will show data . else i will comment again here . Thanks and have a nice day

**Comment by msobh13** [comment]
hey again . i tried again but still no readable data 


{
"hash": "05c224c6344e5e3b6cf8cf428645cca458e1634feed4467623e940949e66b0d7",
"block_id": "840ceb0b5f5438f66f1b50c519228d2a7fce99736fc005f8962ab84a93b0c064",
"tx_type": "Wrapper",
"wrapper_id": "",
"fee_amount_per_gas_unit": "0.000100",
"fee_token": "tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee",
"gas_limit_multiplier": 25000,
"code": "0000000000000000000000000000000000000000000000000000000000000000",
"data": "00a9dfbdbe5e7df4d1412aa179a6df8406e077043540420f000000000000000000000000000000000000000000000000000000000000",
"tx": null
}

**Comment by TuanTQ15** [comment]
any update?

**Comment by TuanTQ15** [comment]
why @rllola close without complete?

**Comment by rllola** [comment]
Only `Decrypted` transaction can have their data read. I have been working on a PR to store the data in its JSON form (which is human readable). The other type of transactions, as far as I can tell, can't be decoded or are even encrypted.

I didn't meant to close it as complete but just to close the issue.
