### ISSUE TITLE
tx/:hash endpoint response format code 

### ISSUE THREAD

**Issue by msobh13** [Zondax/namadexer#111]
linked to  this [https://github.com/Zondax/namadexer/issues/29](https://github.com/Zondax/namadexer/issues/29)

how to know if tx is success or failed .?

**Comment by rllola** [comment]
The answer should have a `return_code` value. If it is `0` it is successful if not it has the error code.

**Comment by msobh13** [comment]
there is no `return_code` in the indexer . the `return_code` can be accessed using direct RPC only . 
in indexer there is `"code":  `  which is not related to what you are saying for example this tx is success while it didnot give 0 in `"code":` in indexer 

`{
"hash": "247fe555718d09a7dd3ebe874cbf66d1f51f4853fed2965dfef978f99ce124b7",
"block_id": "4ccd864d8bd1ad4efe447d5fbfb7ffe6b937273f6fb9d45cfebe3c8f3fe24e44",
"tx_type": "Decrypted",
"wrapper_id": "53485e345a3e4ae8fc714482253c7b97fadbd746bc630c6a6e1cd18fc8e06cbe",
"fee_amount_per_gas_unit": null,
"fee_token": null,
"gas_limit_multiplier": null,
"code": "40e55cdef50e0771eb2b3cfe78b841d988345113f7fbeaa8b158de04589bb9fc",
"data": "00913ca0d1864b758df429d5d5f0d122c7e2fa07eb40420f0000000000000000000000000000000000000000000000000000000000010154dafedf5fdfd33f992c444ee7db31e8bde96c07",
"tx": null
}`

**Comment by msobh13** [comment]
I can see return_code in the db but not in the return result of tx by the server

**Comment by TuanTQ15** [comment]
I do not see the return_code

**Comment by TuanTQ15** [comment]
the same, I do not see return_code in response from the server

**Comment by TuanTQ15** [comment]
@rllola please help
