### ISSUE TITLE
Build error on rc4

### ISSUE THREAD

**Issue by reversesigh** [Zondax/namadexer#126]
```
   Compiling namadexer v0.1.0 (/home/deploy/namadexer)
    Finished dev [unoptimized + debuginfo] target(s) in 58.13s
     Running `target/debug/server`
Error: Config(missing field `port`)
make: *** [Makefile:52: run_server] Error 1
```
I had to checkout the previous version in order to properly launch - otherwise both server and indexer would post this same error. 

`rustc 1.76.0 (07dca489a 2024-02-04)`

**Comment by rllola** [comment]
Yes it is because you are missing the `port` value for the database in your Setting.toml file. We have updated the document to reflect the change you can check it.

I also recommend going with `main`. We have fixed a couple of issues. I will soon create a rc5 tag.
