### ISSUE TITLE
error: "Unexpected variant tag: 49"  on block 18541.

### ISSUE THREAD

**Issue by hkey0** [Zondax/namadexer#131]
I get this error on block 18541.
```
  2024-02-15T03:31:15.296035Z  INFO namadexer::database: Saving tx_bond transaction
    at src/database.rs:656
    in namadexer::database::save_transactions with block_height: 18541
    in namadexer::database::save_block_impl with network: "public_testnet_15"
    in namadexer::database::save_block

OpenTelemetry trace error occurred. Exporter jaeger encountered the following error(s): thrift agent failed on transportation layer, not open, Connection refused (os error 111)
  2024-02-15T03:31:15.296791Z ERROR namadexer::indexer: Closing block producer task due to an error saving last block: Configuration error: Unexpected variant tag: 49
    at src/indexer/mod.rs:229

  2024-02-15T03:31:15.297061Z  WARN namadexer::indexer: Block consumer closed, exiting producer
    at src/indexer/mod.rs:278

OpenTelemetry trace error occurred. Exporter jaeger encountered the following error(s): thrift agent failed on transportation layer, not open, Connection refused (os error 111)
Error: IO(Custom { kind: InvalidData, error: "Unexpected variant tag: 49" })
```

**Comment by StoneMac65** [comment]
with network: "public_testnet_15"??

**Comment by rllola** [comment]
Hey @hkey0 
Could you confirm if it was on public testnet 15 or shielded expedition ?

**Comment by bombermine3** [comment]
Shielded expedition
```
2024-02-15T09:10:37.119164Z  INFO namadexer::database: Saving tx_bond transaction
    at src/database.rs:656
    in namadexer::database::save_transactions with block_height: 18541
    in namadexer::database::save_block_impl with network: "shielded_expedition"
    in namadexer::database::save_block

  2024-02-15T09:10:37.119509Z ERROR namadexer::indexer: Closing block producer task due to an error saving last block: Configuration error: Unexpected variant tag: 49
    at src/indexer/mod.rs:229

Error: IO(Custom { kind: InvalidData, error: "Unexpected variant tag: 49" })
make: *** [Makefile:49: run_indexer] Error 1
```

**Comment by rllola** [comment]
I have hit the same error. Looking at this now.

**Comment by rllola** [comment]
I have found the culprit `167e4f8d839b77b466d8249775bb71be6659801c8955ce171236f7fad7575a3f`. It is a bonding transaction but we just can't decode it. I am not entirely sure it is a valid transaction and I think that's the problem.

**Comment by msobh13** [comment]
FYI i got same err 
`ERROR namadexer::indexer: Closing block producer task due to an error saving last block: Configuration error: Unexpected variant tag: 49`

**Comment by hkey0** [comment]
> I have found the culprit `167e4f8d839b77b466d8249775bb71be6659801c8955ce171236f7fad7575a3f`. It is a bonding transaction but we just can't decode it. I am not entirely sure it is a valid transaction and I think that's the problem.

There are other transactions that cannot be decoded:
`FE496E56C45653CEC6AA24FF209CDB8443889E02A0763B0A2FD745A05DDB4184`
`8E526CC7C24BDFA9A2218B82B5996E461922508320683335D199E573561D1194`
`8E526CC7C24BDFA9A2218B82B5996E461922508320683335D199E573561D1194`

**Comment by rllola** [comment]
I have found that those transaction have failed... Probably because the data are not well encoded.

**Comment by zenodeapp** [comment]
> I have found the culprit `167e4f8d839b77b466d8249775bb71be6659801c8955ce171236f7fad7575a3f`. It is a bonding transaction but we just can't decode it. I am not entirely sure it is a valid transaction and I think that's the problem.

https://github.com/Zondax/namadexer/issues/129#issuecomment-1945567895

😂...I uh, probably have to say I'm sorry.

**Comment by hubofvalley** [comment]
please give me the solution for this problem, it's really confusing
