### ISSUE TITLE
Checksum rotation

### ISSUE THREAD

**Issue by egasimus** [Zondax/namadexer#139]
As far as I understand, the checksum file that is downloaded during the build is required to decrypt transactions and populate the `tx_*` tables.

But, those checksums are different for every version of the node software - and the version of the node doesn't seem to be reported by the RPC API (which makes sense to me from a security perspective.)

So, for my initial runs of Namadexer, there happened to be a link to the appropriate checksum files [on the Luminara testnet info page](https://testnet.luminara.icu/). I was able to mount that into the container and, supposedly, decrypt.

However, turned out there was no real activity to index on that chain. So, we switched to the ITRocket one. And, what I had to do in order to get that working, was start pulling [past versions of `checksums.json` from GitHub](https://github.com/anoma/namada/commits/main/wasm/checksums.json) and mounting them into the container, one by one - starting with the latest 0.31.4, all the way down to (thankfully, only) 0.31.1. This worked, and now I'm indexing away!

Therefore, the issue: I think it's fair to assume chain upgrades are likely to change the checksums. So, wouldn't the indexer need to have access to *all* versions of those checksums, plus the block numbers where switchover happens from each version to the next one, in order to be able to index decrypted data across chain upgrades?

:link: [zboto Link](https://app.clickup.com/t/8694f92dy)

**Comment by rllola** [comment]
>  So, wouldn't the indexer need to have access to all versions of those checksums

Yes you are right. So far they always reset the network we didn't faced this issue but we should keep a history of checksum.json file and the transaction have a code that should match at least one in either file. This is how we can know what kind of transaction it is.

We discussed it with developers but they didn't have a plan for upgrade yet.

Also please note that we are working on another way to have the decrypted info in the database that would remove the need for the `tx_*` table. It will simplify things greatly but we want to be sure it won't impact too much the performance.

**Comment by ainhoa-a** [comment]
This indexer is no longer being maintained by request of heliax/namada team and it will be archived soon.
