### ISSUE TITLE
Query vote_proposal always return null without error

### ISSUE THREAD

**Issue by suntzu93** [Zondax/namadexer#140]
I'm trying to query proposal but always return null.

`curl -H 'Content-Type: application/json' localhost:30303/tx/vote_proposal/1`

output : 

`null`

**Comment by zenodeapp** [comment]
This might be related to not having `indexer="kv"` in your `config.toml` of RPC node.

**Comment by suntzu93** [comment]
> This might be related to not having `indexer="kv"` in your `config.toml` of RPC node.
> 
> You will have to reset your node if you do this (so let it resync from 0).

My rpc synced with `indexer="kv"` from block 1

**Comment by rllola** [comment]
@suntzu93 Which version of the indexer are you running ? Is it tag [v0.1.0-rc.5](https://github.com/Zondax/namadexer/releases/tag/v0.1.0-rc.5)

**Comment by suntzu93** [comment]
> @suntzu93 Which version of the indexer are you running ? Is it tag [v0.1.0-rc.5](https://github.com/Zondax/namadexer/releases/tag/v0.1.0-rc.5)

yes, I'm using [v0.1.0-rc.5](https://github.com/Zondax/namadexer/releases/tag/v0.1.0-rc.5)
