### ISSUE TITLE
Network cannot contain "."

### ISSUE THREAD

**Issue by opsecx** [Zondax/namadexer#143]
Getting this when trying "make run_server": Running `target/debug/server`
thread 'main' panicked at src/config.rs:241:17:
network cannot contains '.' (example of valid network 'public-testnet-14')
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:52: run_server] Error 101

Obviously with the current tested shielded network name format which does contain a period, this is not great.? Please advise

**Comment by rllola** [comment]
You have your answer in the error message. You should remove the '.' because it is not part of the network name it is the chain ID.

In your case for shielded expeditino you should have `network = "shielded-expedition"`

**Comment by opsecx** [comment]
> You have your answer in the error message. You should remove the '.' because it is not part of the network name it is the chain ID.
> 
> 
> 
> In your case for shielded expedition you should have `network = "shielded-expedition"`.
> 
> 
> 
> EDIT: we are actually going to change the variable name to `chain_name` because people are confused between network and chain ID.

alright thanks.
