### ISSUE TITLE
Indexer halts

### ISSUE THREAD

**Issue by opsecx** [Zondax/namadexer#166]
Checked out latest version of indexer on a separate server, to see how it works (still running older in production, and request for views/old tables still apply).

The new version of the indexer randomly (and periodically) halts with following error code:

Error: Timeout(Elapsed(()))
make: *** [Makefile:49: run_indexer] Error 1

(where the older indexer would "get stuck" and need a restart)

**Comment by rllola** [comment]
Yes I did that as a patch. If you are using docker you can set it to `always-restart` and it would keep indexing.

They finally merged the patch for timeout so for next release it should be fixed.

(closing this as it is a duplicate to the first issue).

**Comment by opsecx** [comment]
Oh ok so this was a fix so it wouldn't freeze?
