### ISSUE TITLE
Error Types

### ISSUE THREAD

**Issue by jipan76** [Zondax/namadexer#169]
5 | use namada_sdk::types:🔑:common::PublicKey;
  |                 ^^^^^ could not find types in namada_sdk

**Comment by rllola** [comment]
Which version are you using ?

**Comment by jipan76** [comment]
> Which version are you using ?

in cargo.toml 0.2.0 version

**Comment by jipan76** [comment]
solved but i got new error

Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/root/namadexer/checksums.json" to rootfs at "/app/checksums.json": mount /root/namadexer/checksums.json:/app/checksums.json (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
make: *** [Makefile:58: compose] Error 1
