### ISSUE TITLE
hash empty in transactions table

### ISSUE THREAD

**Issue by opsecx** [Zondax/namadexer#170]
After trying the newer versions, it seems the hash (txid) field in transactions are almost always empty. Shouldn't that either be populated or empty? (I realize it's probably part of the json model but still). Left some comments on the structure of the views in the closed issue on that btw, if anyone has time to look.

**Comment by LUNA007KING** [comment]
I also got null response when trying to get transaction details.

**Comment by rllola** [comment]
I would need more information... I don't have empty hash and the table doesn't allow for null (see table creation `        "CREATE TABLE IF NOT EXISTS {}.transactions (hash BYTEA NOT NULL, ...`).

@LUNA007KING Can you give an example of txid that return null ?

**Comment by opsecx** [comment]
> I would need more information... I don't have empty hash and the table doesn't allow for null (see table creation `        "CREATE TABLE IF NOT EXISTS {}.transactions (hash BYTEA NOT NULL, ...`).
> 
> 
> 
> @LUNA007KING Can you give an example of txid that return null ?

On a closer look I think this was a query error on my part. doublechecking, but most rows have populated has field.

**Comment by rllola** [comment]
Closing this issue for now. Will re-open if new infos are provided.
