### ISSUE TITLE
Mount Checksum Json Error

### ISSUE THREAD

**Issue by jipan76** [Zondax/namadexer#171]
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/root/namadexer/checksums.json" to rootfs at "/app/checksums.json": mount /root/namadexer/checksums.json:/app/checksums.json (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
make: *** [Makefile:58: compose] Error 1

Can anyone help?

**Comment by rllola** [comment]
You might be missing the `checksums.json` file to be mounted. Can you try running `make download-checksum` ?

**Comment by Fr33sson** [comment]
The script creates a directory named checksums.json instead of downloading the file to the main directory. I had to download it manually and then it started.

**Comment by rllola** [comment]
> The script creates a directory named checksums.json instead of downloading the file to the main directory. I had to download it manually and then it started.

It is is docker that create the empty folder if the file is not present. We can improve the dockerfile to download the checksums.json file if missing to avoid confusion.
