### ISSUE TITLE
Views need updating

### ISSUE THREAD

**Issue by opsecx** [Zondax/namadexer#174]
As per conversation about this in discord: There are some discrepancies between the old table formats and the views that are meant to convey the same data model. Here is a brief rundown of what I found so far (may add more in comments below): (will leave to your judgment which updates are better and which should be left as old. the main thing I can't be without are tx_id)

view tx_transfert vs old table tx_transfer (typo?)
view tx_vote_proposal vs old table vote_proposal (personally prefer the latter)
missing tx_id column in both views tx_transfert and tx_vote_proposal
(maybe also other views, I only use these two)
column "id" in view tx_vote_proposal vs column "vote_proposal_id" in table vote_proposal 
missing "key" and "shielded" columns in view tx_transfert (I didn't use these though so no big deal for me if dropped)

**Comment by rllola** [comment]
> view tx_transfert vs old table tx_transfer (typo?)
Yeah that's a typo. Good catch.

>  view tx_vote_proposal vs old table vote_proposal (personally prefer the latter)
I am following the standard in the contract name (see https://github.com/anoma/namada/tree/main/wasm/wasm_source/src).

>  missing tx_id column in both views tx_transfert and tx_vote_proposal
I think it is missing everywhere... I am adding it.

>  column "id" in view tx_vote_proposal vs column "vote_proposal_id" in table vote_proposal
I am using the same name in namada source code

>  missing "key" and "shielded" columns in view tx_transfert (I didn't use these though so no big deal for me if dropped)
Good catch. I have missed them too.

**Comment by opsecx** [comment]
> > view tx_transfert vs old table tx_transfer (typo?)
> 
> 
> 
> Yeah that's a typo. Good catch.
> 
> 
> 
> >  view tx_vote_proposal vs old table vote_proposal (personally prefer the latter)
> 
> 
> 
> I am following the standard in the contract name (see https://github.com/anoma/namada/tree/main/wasm/wasm_source/src).
> 
> 
> 
> >  missing tx_id column in both views tx_transfert and tx_vote_proposal
> 
> 
> 
> I think it is missing everywhere... I am adding it.
> 
> 
> 
> >  column "id" in view tx_vote_proposal vs column "vote_proposal_id" in table vote_proposal
> 
> 
> 
> I am using the same name in namada source code
> 
> 
> 
> >  missing "key" and "shielded" columns in view tx_transfert (I didn't use these though so no big deal for me if dropped)
> 
> 
> 
> Good catch. I have missed them too.

Awesome, thanks!

**Comment by opsecx** [comment]
There is an issue with this though, created a new issue and pr just fyi.
