### ISSUE TITLE
cant start indexer with new db

### ISSUE THREAD

**Issue by Zlkcyber** [Zondax/namadexer#178]
already delete my oldest db because stuck, and when im upgrade and starting new db i got this
 
`src/indexer/mod.rs:88
    in namadexer::indexer::get_block with block_height: 1, chain_name: "shielded_expedition"
    2024-03-29T13:53:11.213740Z  WARN namadexer::indexer: Failed to retreive block at height 1.`

**Comment by rllola** [comment]
Hi @Zlkcyber 
Yes we are aware of it. The new node doesn't provide access to the old blocks unfortunately. If you have the backup the shielded-expedition you can start the old namada version v0.31.9 using this.

We could also provide in the indexer an option to start at the block `237907`.

**Comment by Zlkcyber** [comment]
@rllola hmm yes i just change utils.rs to latest block and its work

**Comment by rllola** [comment]
If you want to start from 0 you can use this endpoint (http://51.159.167.32:26657) and switch once it is at 237906.

It is a temporary solution. We are working at providing a stable one and include in the indexer as a fallback.

**Comment by egasimus** [comment]
That node is dead now :( Any alternatives?
