### ISSUE TITLE
Views include too much data

### ISSUE THREAD

**Issue by opsecx** [Zondax/namadexer#186]
The new views include transactions regardless of completion status. Made a pr to fix, note there may be some revision history issues in it, I hope I got it correct now.

:link: [zboto Link](https://app.clickup.com/t/8694f92bb)

**Comment by opsecx** [comment]
https://github.com/Zondax/namadexer/pull/185

**Comment by opsecx** [comment]
Do we need to do something similar for the rest of the views? (and maybe improve on any additional data that would be useful?)

**Comment by rllola** [comment]
Yes, we probably need to do it on the other views.

**Comment by opsecx** [comment]
I'm wondering a bit if this is the ideal way, or if it would be better to rework so all tx are included, but with a new column indicating either success or fail of tx. Not sure what would be ideal

**Comment by rllola** [comment]
I was wondering the same things. I am in favor of having a new column like you propose. Having all the information is better than having something implicit.
You can also have a filter when querying your view if you only want the successful transaction but doing it the other way is a bit more work.

**Comment by opsecx** [comment]
Agree, probably good to include all, but necessary with the additional column. But maybe then a human readable format rather than just return-code

**Comment by rllola** [comment]
I will try to see if I can find the error that match the return code. `0` is obviously success but for the rest I don't have this information.

**Comment by opsecx** [comment]
Yes was wondering about those.. Think it's mainly 0 and 1 in use, but better to have it complete.

**Comment by opsecx** [comment]
I do feel like the data model is constantly changing far too much. views changing is less problematic, but still problematic from a usecase-perspective when compatibility breaks (like it will again when the above-mentioned improvement is introduced - and in subtle ways even for those not paying attention here on git). tables changing (like one of the latest prs) that requires a resync really are bothersome. resyncing my indexer again now for idk which time

**Comment by ainhoa-a** [comment]
This indexer is no longer being maintained by request of heliax/namada team and it will be archived soon.
