### ISSUE TITLE
Denomination is different for different transaction types

### ISSUE THREAD

**Issue by cryptosystems6300** [Zondax/namadexer#194]
![image](https://github.com/Zondax/namadexer/assets/110590814/cc726382-a475-41db-b912-44702806f480)

https://namada-testnet-indexer.itrocket.net/address/tnam1qpuxpeuwxwdpuy3tf7fylnyw43y3ccsyzg8nxr30

Some transactions return an integer, some return a float.

**Comment by rllola** [comment]
It is because they are different kind of transaction even if they share the same field name they are different types. Unfortunately we cannot do anything for this.
