### ISSUE TITLE
Suggestions views

### ISSUE THREAD

**Issue by opsecx** [Zondax/namadexer#202]
Some suggestions for making the views more informative/rich if that's the way we move:

- include block height and block date_time in all views
- include success/fail as previously discussed

May add more as they come to mind.

:link: [zboto Link](https://app.clickup.com/t/8694f92ae)

**Comment by opsecx** [comment]
Made a temporary fix for successful tx only in views in pr https://github.com/Zondax/namadexer/pull/206

**Comment by ainhoa-a** [comment]
This indexer is no longer being maintained by request of heliax/namada team and it will be archived soon.
