### ISSUE TITLE
Memo field encoding

### ISSUE THREAD

**Issue by opsecx** [Zondax/namadexer#204]
I think it would make more sense if the memo field in transactions table was decoded and not hex.?

:link: [zboto Link](https://app.clickup.com/t/8694f7vt7)

**Comment by opsecx** [comment]
In any case for the time being, added a fix/feat for views with decoded memo field in https://github.com/Zondax/namadexer/pull/206

**Comment by ainhoa-a** [comment]
This indexer is no longer being maintained by request of heliax/namada team and it will be archived soon.
