### ISSUE TITLE
Better indexing of proposals

### ISSUE THREAD

**Issue by opsecx** [Zondax/namadexer#205]
Atm, init-proposal transactions are indexed via view, but doesn't give any info on the proposal itself as it ultimately exists on-chain, only what has been submitted with the init-tx. Would be good to have it tied to how the proposal ends on-chain somehow.

:link: [zboto Link](https://app.clickup.com/t/8694g24yj)

**Comment by ainhoa-a** [comment]
This indexer is no longer being maintained by request of heliax/namada team and it will be archived soon.
