### ISSUE TITLE
Elements in `tx_hashes` list should be formatted

### ISSUE THREAD

**Issue by Fraccaman** [Zondax/namadexer#22]
Querying blocks returns information about the querying block but the items inside the list of transactions are not formatted properly and can't be used to query data about the actual transaction.

**Comment by neithanmo** [comment]
Currently,  we are returning the tx_hash(es) formatted as a hex string that a block contains. You can use any of those hashes to retrieve the specific transaction information, by doing so we keep the block data structure simple, containing only relevant information that can be used to query further information.

@Fraccaman  What other information regarding transactions do You consider important/useful to include in the data the block endpoint returns?

**Comment by Fraccaman** [comment]
the block endpoint returns the list of hashes formatted like:

**Comment by rllola** [comment]
You want something like this ?
```
{
  "block_id": "70efb92d4382a756c1231e178261495be82d71b3478ef5367c1f6940fa2ed2c6",
  ...
  "tx_hashes": [
    "c069aa769512ebe66a4ad1d565a7d944fb03884a75c2c48640b2e52fecef9f31"
  ]
}

```
