### ISSUE TITLE
Following tx should be saved into the indexer

### ISSUE THREAD

**Issue by ainhoa-a** [Zondax/namadexer#33]
- [x] tx_bond: self-bond source is `null` please check
- [x]  tx_change_validator_commission
- [x]  tx_ibc
- [x] tx_init_account
- [x] tx_init_validator
- [x]  tx_resign_steward
- [x]  tx_reveal_pk
- [x] tx_update_account
- [x] tx_update_steward_commission
- [x] tx_vote_proposal
- [x] tx_withdraw
- [x]  tx_transfer (should be already implemented)

**Comment by neithanmo** [comment]
Via #38 
There are still missing new tables to track account updates

**Comment by neithanmo** [comment]
completed via #43
