### ISSUE TITLE
Indexer stops syncing due to foreign key constraint "fk_tx_id" violation

### ISSUE THREAD

**Issue by appferreira** [Zondax/namadexer#76]
The indexer service blocks syncing and exits due to a key constraint violation - please see the whole log below : 

> indexer   |   2024-01-02T20:27:36.411463Z  INFO namadexer::indexer: Got block 104715
> indexer   |     at src/indexer/mod.rs:51
> indexer   |     in namadexer::indexer::get_block with block_height: 104715
> indexer   | 
> indexer   |   2024-01-02T20:27:36.481022Z  INFO namadexer::database: Saving tx_transfer transaction
> indexer   |     at src/database.rs:652
> indexer   |     in namadexer::database::save_transactions with block_results: Response { height: block::Height(104714), txs_results: Some([ExecTxResult { code: Ok, data: b"", log: "", info: "", gas_wanted: 0, gas_used: 0, events: [], codespace: "" }]), finalize_block_events: [], begin_block_events: None, end_block_events: Some([Event { kind: "applied", attributes: [EventAttribute { key: "code", value: "0", index: true }, EventAttribute { key: "height", value: "104714", index: true }, EventAttribute { key: "log", value: "", index: true }, EventAttribute { key: "initialized_accounts", value: "[]", index: true }, EventAttribute { key: "hash", value: "8DABC5B24CD2C66B66276E72AAA719D99BB53E67A2D43840BC4EC78849037463", index: true }, EventAttribute { key: "gas_used", value: "10366", index: true }, EventAttribute { key: "info", value: "Transaction is valid. Gas used: 10366; Changed keys: #tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah/head-tx, #tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah/tx-8418, #tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1q9mjvqd45u7w54kee2aquugtv7vn7h3xrcrau7xy/balance/#tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah, #tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1q9mjvqd45u7w54kee2aquugtv7vn7h3xrcrau7xy/balance/#tnam1qxdn8dwj8pkk0gz7alynfdazxahupsgrhy7l494s; VPs result:  Accepted: tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah, tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv, tnam1qxdn8dwj8pkk0gz7alynfdazxahupsgrhy7l494s;", index: true }] }]), validator_updates: [], consensus_param_updates: None, app_hash: AppHash() }
> indexer   |     in namadexer::database::save_block_impl with block_results: Response { height: block::Height(104714), txs_results: Some([ExecTxResult { code: Ok, data: b"", log: "", info: "", gas_wanted: 0, gas_used: 0, events: [], codespace: "" }]), finalize_block_events: [], begin_block_events: None, end_block_events: Some([Event { kind: "applied", attributes: [EventAttribute { key: "code", value: "0", index: true }, EventAttribute { key: "height", value: "104714", index: true }, EventAttribute { key: "log", value: "", index: true }, EventAttribute { key: "initialized_accounts", value: "[]", index: true }, EventAttribute { key: "hash", value: "8DABC5B24CD2C66B66276E72AAA719D99BB53E67A2D43840BC4EC78849037463", index: true }, EventAttribute { key: "gas_used", value: "10366", index: true }, EventAttribute { key: "info", value: "Transaction is valid. Gas used: 10366; Changed keys: #tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah/head-tx, #tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah/tx-8418, #tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1q9mjvqd45u7w54kee2aquugtv7vn7h3xrcrau7xy/balance/#tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah, #tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1q9mjvqd45u7w54kee2aquugtv7vn7h3xrcrau7xy/balance/#tnam1qxdn8dwj8pkk0gz7alynfdazxahupsgrhy7l494s; VPs result:  Accepted: tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah, tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv, tnam1qxdn8dwj8pkk0gz7alynfdazxahupsgrhy7l494s;", index: true }] }]), validator_updates: [], consensus_param_updates: None, app_hash: AppHash() }, network: "public_testnet_15"
> indexer   |     in namadexer::database::save_block with block_results: Response { height: block::Height(104714), txs_results: Some([ExecTxResult { code: Ok, data: b"", log: "", info: "", gas_wanted: 0, gas_used: 0, events: [], codespace: "" }]), finalize_block_events: [], begin_block_events: None, end_block_events: Some([Event { kind: "applied", attributes: [EventAttribute { key: "code", value: "0", index: true }, EventAttribute { key: "height", value: "104714", index: true }, EventAttribute { key: "log", value: "", index: true }, EventAttribute { key: "initialized_accounts", value: "[]", index: true }, EventAttribute { key: "hash", value: "8DABC5B24CD2C66B66276E72AAA719D99BB53E67A2D43840BC4EC78849037463", index: true }, EventAttribute { key: "gas_used", value: "10366", index: true }, EventAttribute { key: "info", value: "Transaction is valid. Gas used: 10366; Changed keys: #tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah/head-tx, #tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah/tx-8418, #tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1q9mjvqd45u7w54kee2aquugtv7vn7h3xrcrau7xy/balance/#tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah, #tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv/#tnam1q9mjvqd45u7w54kee2aquugtv7vn7h3xrcrau7xy/balance/#tnam1qxdn8dwj8pkk0gz7alynfdazxahupsgrhy7l494s; VPs result:  Accepted: tnam1pcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzmefah, tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv, tnam1qxdn8dwj8pkk0gz7alynfdazxahupsgrhy7l494s;", index: true }] }]), validator_updates: [], consensus_param_updates: None, app_hash: AppHash() }
> indexer   | 
> postgres  | 2024-01-02 20:27:36.485 UTC [34] ERROR:  insert or update on table "tx_transfer" violates foreign key constraint "fk_tx_id"
> postgres  | 2024-01-02 20:27:36.485 UTC [34] DETAIL:  Key (tx_id)=(\x8dabc5b24cd2c66b66276e72aaa719d99bb53e67a2d43840bc4ec78849037463) is not present in table "transactions".
> postgres  | 2024-01-02 20:27:36.485 UTC [34] STATEMENT:  INSERT INTO public_testnet_15.tx_transfer(
> postgres  |                                     tx_id,
> postgres  |                                     source, 
> postgres  |                                     target, 
> postgres  |                                     token,
> postgres  |                                     amount,
> postgres  |                                     key,
> postgres  |                                     shielded
> postgres  |                                 )VALUES ($1, $2, $3, $4, $5, $6, $7)
> indexer   |   2024-01-02T20:27:36.485362Z ERROR namadexer::indexer: Closing block producer task due to an error saving last block: Database error: error returned from database: insert or update on table "tx_transfer" violates foreign key constraint "fk_tx_id"
> indexer   |     at src/indexer/mod.rs:225
> indexer   | 
> indexer   | Error: DB(Database(PgDatabaseError { severity: Error, code: "23503", message: "insert or update on table \"tx_transfer\" violates foreign key constraint \"fk_tx_id\"", detail: Some("Key (tx_id)=(\\x8dabc5b24cd2c66b66276e72aaa719d99bb53e67a2d43840bc4ec78849037463) is not present in table \"transactions\"."), hint: None, position: None, where: None, schema: Some("public_testnet_15"), table: Some("tx_transfer"), column: None, data_type: None, constraint: Some("fk_tx_id"), file: Some("ri_triggers.c"), line: Some(2528), routine: Some("ri_ReportViolation") }))
> indexer exited with code 1

**Comment by rllola** [comment]
Hi @appferreira 

Did you reset your database with the new testnet ?

**Comment by appferreira** [comment]
Hi @rllola . Thanks for your fast reply.
Yes, everything is reset. We are starting the node on the latest version public-testnet-15.0dacadb8d663, tested on three different instances. However, the error occurs at different block heights; previously, we faced failure always at the same block with the error: "ERROR namadexer::indexer: Closing block producer task due to an error saving the last block: Database error: error returned from database: duplicate key value violates unique constraint 'vote_proposal_pkey'". We are unable to advance to block 6525. Having said that, I created a trigger to adjust the field value, ensuring that the new value is unique in the table and that there are no conflicts with duplicate values. So, after the insertion of almost 100k blocks, we are facing this other failure.

**Comment by rllola** [comment]
Hi @appferreira 
I am looking into this now. If this kind of error is shown it might be because we are missing transactions when indexing and that wouldn't be good.

Now that we have a stable-ish testnet I can run a full test.

There is anther option and that would be to disable creating index from the config file. However that would make the server part really slow.

**Comment by romanv1812** [comment]
> Hi @rllola . Thanks for your fast reply. Yes, everything is reset. We are starting the node on the latest version public-testnet-15.0dacadb8d663, tested on three different instances. However, the error occurs at different block heights; previously, we faced failure always at the same block with the error: "ERROR namadexer::indexer: Closing block producer task due to an error saving the last block: Database error: error returned from database: duplicate key value violates unique constraint 'vote_proposal_pkey'". We are unable to advance to block 6525. Having said that, I created a trigger to adjust the field value, ensuring that the new value is unique in the table and that there are no conflicts with duplicate values. So, after the insertion of almost 100k blocks, we are facing this other failure.

I also get an error on block 6525
