### ISSUE TITLE
Error happens during indexing Shielded Expedition chain

### ISSUE THREAD

**Issue by Liver-23** [Zondax/namadexer#85]
The block can be different, one of the first, but code lines are the same all the time
```
2024-02-01T18:27:05.860363Z  INFO namadexer::indexer: Got block 5
    at src/indexer/mod.rs:51
    in namadexer::indexer::get_block with block_height: 5

  2024-02-01T18:27:05.861284Z ERROR namadexer::indexer: Closing block producer task due to an error saving last block: Invalid Transaction data
    at src/indexer/mod.rs:225

Error: InvalidTxData
make: *** [Makefile:49: run_indexer] Error 1
```

**Comment by Michel-Leidson** [comment]
I'm also getting the same error.

**Comment by gnosed** [comment]
same error, the indexer crashes when it gets wrong txs

**Comment by blockhunters-dev** [comment]
same here, maybe because the indexer builds on namada v0.28.1? 

tried to upgrade to v0.31.0, but I was unable to do it

**Comment by rllola** [comment]
Hey!
I think yes it is because of a breaking change in the transaction format. Indeed I also believe we need to upgrade the namada lib. I will do it ASAP.

**Comment by blockhunters-dev** [comment]
Pushed a PR with the upgrades, but I'm not sure everything is right

**Comment by Liver-23** [comment]
> Pushed a PR with the upgrades, but I'm not sure everything is right

it works, already tried it yesterday

**Comment by mrost1** [comment]
2024-02-02T20:25:02.685751Z ERROR namadexer::indexer: Closing block producer task due to an error saving last block: Invalid Transaction data

So we need to wait for new release and then re-install to fix this problem?
