### ISSUE TITLE
network cannot contains '.'

### ISSUE THREAD

**Issue by Pa1amar** [Zondax/namadexer#86]
```Attaching to indexer, postgres, server
indexer   | thread 'main' panicked at src/config.rs:225:17:
indexer   | network cannot contains '.' (example of valid network 'public-testnet-14')
indexer   | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
indexer exited with code 101
server    | thread 'main' panicked at src/config.rs:225:17:
server    | network cannot contains '.' (example of valid network 'public-testnet-14')
server    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
server exited with code 101```

**Comment by blockhunters-dev** [comment]
You can replace the "." with a "_" as a quickfix

**Comment by rllola** [comment]
Hey @blockhunters-dev 

What network name did you put in the config file ?

**Comment by blockhunters-dev** [comment]
I used `shielded-expedition-b40d8e9055`.

Tried to remove the check in the code but that resulted in postgres errors so I figured out that it doesn't work so well with '.' in schema names

**Comment by rllola** [comment]
Yes indeed the postgres schema are not a fans of '.' so we give as the network id only the name of the testnet and not the chaind ID with the hash checksum.

So it would look like this `shielded-expedition`. I will try to clarify this in the documentation. Sorry for the confusion.
