### ISSUE TITLE
 database: column "vote_default" of relation "vote_proposal" does not exist

### ISSUE THREAD

**Issue by msobh13** [Zondax/namadexer#91]
deleted db recreate and sync from scratch still the same 
 
database: column "vote_default" of relation "vote_proposal" does not exist

` 2024-02-03T09:38:03.122142Z ERROR namadexer::indexer: Closing block producer task due to an error saving last block: Database error: error returned from database: column "vote_default" of relation "vote_proposal" does not exist
    at src/indexer/mod.rs:225

Error: DB(Database(PgDatabaseError { severity: Error, code: "42703", message: "column \"vote_default\" of relation \"vote_proposal\" does not exist", detail: None, hint: None, position: Some(Original(168)), where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("parse_target.c"), line: Some(1061), routine: Some("checkInsertTargets") }))
`

**Comment by rllola** [comment]
I am fixing this ASAP. My bad I pushed a fix on the new version and miss this. Thank you for reporting.

**Comment by hkey0** [comment]
> I am fixing this ASAP. My bad I pushed a fix on the new version and miss this. Thank you for reporting.

Is there any way to pass this for now?

**Comment by dimiandre** [comment]
reference #92
